# Deploy workflow for VividWealth app
# Runs on tag releases or manual trigger
# Required secrets: EXPO_TOKEN, SLACK_WEBHOOK_URL, GITHUB_TOKEN, APPLE_ID, ASC_APP_ID, APPLE_TEAM_ID, GOOGLE_SERVICE_ACCOUNT_KEY

name: VividWealth Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      
      - name: Install Expo CLI
        run: npm install -g eas-cli
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Set Environment Variables
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" || -z "${{ github.event.inputs.environment }}" && ! "${{ github.ref }}" =~ ^refs/tags/v ]]; then
            echo "APP_ENV=staging" >> $GITHUB_ENV
            echo "PROFILE=preview" >> $GITHUB_ENV
            echo "Using staging environment with preview profile"
          else
            echo "APP_ENV=production" >> $GITHUB_ENV
            echo "PROFILE=production" >> $GITHUB_ENV
            echo "Using production environment with production profile"
          fi
      
      - name: Set Version from Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          
          # Update app.json with the version
          jq ".expo.version = \"$VERSION\" | .expo.ios.buildNumber = \"$VERSION\" | .expo.android.versionCode = $(echo $VERSION | tr -d '.' | sed 's/^[0]*//')" app.json > app.json.tmp
          mv app.json.tmp app.json
      
      - name: Validate iOS Submission Credentials
        if: env.PROFILE == 'production'
        run: |
          if [ -z "${{ secrets.APPLE_ID }}" ] || [ -z "${{ secrets.ASC_APP_ID }}" ] || [ -z "${{ secrets.APPLE_TEAM_ID }}" ]; then
            echo "::error::Missing iOS submission credentials. Please ensure APPLE_ID, ASC_APP_ID, and APPLE_TEAM_ID secrets are set."
            exit 1
          fi
          echo "iOS submission credentials validated"
      
      - name: Validate Android Submission Credentials
        if: env.PROFILE == 'production'
        run: |
          # Create service account key file from secret
          if [ -z "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" ]; then
            echo "::error::Missing Google Service Account Key. Please ensure GOOGLE_SERVICE_ACCOUNT_KEY secret is set."
            exit 1
          fi
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > google-service-account.json
          echo "GOOGLE_SERVICE_ACCOUNT_KEY_PATH=$(pwd)/google-service-account.json" >> $GITHUB_ENV
          echo "Android submission credentials validated"
      
      - name: Build Production App
        if: env.PROFILE == 'production'
        run: npx eas-cli build --platform all --profile production --non-interactive
      
      - name: Submit Production App
        if: env.PROFILE == 'production'
        run: |
          npx eas-cli submit --platform ios --profile production --non-interactive --path latest
          npx eas-cli submit --platform android --profile production --non-interactive --path latest
        env:
          EXPO_APPLE_ID: ${{ secrets.APPLE_ID }}
          EXPO_ASC_APP_ID: ${{ secrets.ASC_APP_ID }}
          EXPO_APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          EXPO_ANDROID_KEY_PATH: ${{ env.GOOGLE_SERVICE_ACCOUNT_KEY_PATH }}
      
      - name: Build Staging App
        if: env.PROFILE == 'preview'
        run: npx eas-cli build --platform all --profile preview --non-interactive
      
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.APP_VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          files: |
            *.apk
            *.ipa
            *.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Notify Deployment Success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ":rocket: Successfully deployed VividWealth app version ${{ env.APP_VERSION || github.sha }} to ${{ github.event.inputs.environment || 'production' }}!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: Notify Deployment Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ":x: Failed to deploy VividWealth app to ${{ github.event.inputs.environment || 'production' }}!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Cleanup Credentials
        if: always()
        run: |
          if [ -f "$(pwd)/google-service-account.json" ]; then
            rm -f "$(pwd)/google-service-account.json"
          fi 