# Development workflow for VividWealth app
# Builds development client for team testing
# Required secrets: EXPO_TOKEN, EXPO_USERNAME, EXPO_PASSWORD

name: VividWealth Development

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build platform'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android

jobs:
  build-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      
      - name: Install Expo CLI
        run: npm install -g eas-cli
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Expo login
        run: |
          echo "Using Expo CLI to login"
          npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }} --non-interactive
      
      - name: Set Environment Variables
        run: |
          echo "APP_ENV=development" >> $GITHUB_ENV
          echo "Using development environment"
      
      - name: Build Development Client
        run: npx eas-cli build --profile development --platform ${{ github.event.inputs.platform }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
      - name: Upload Development Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: development-build-${{ github.run_id }}
          path: |
            *.apk
            *.ipa
          retention-days: 14
      
      - name: Notify Team
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ":sparkles: New development build is available for testing!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success() 