# Rollback workflow for VividWealth app
# Triggered manually to roll back to a previous version
# Required secrets: EXPO_TOKEN, SLACK_WEBHOOK_URL, SENTRY_AUTH_TOKEN, SENTRY_ORG, SENTRY_PROJECT

name: VividWealth Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to roll back to (e.g., v1.0.0)'
        required: true
        type: string
      confirm:
        description: 'Type "CONFIRM" to proceed with rollback'
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        if: github.event.inputs.confirm != 'CONFIRM'
        run: |
          echo "Rollback not confirmed. Please type 'CONFIRM' in the confirm field to proceed."
          exit 1
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Validate version tag
        run: |
          if ! git tag -l | grep -q "^${{ github.event.inputs.version }}$"; then
            echo "Version tag ${{ github.event.inputs.version }} does not exist."
            echo "Available tags:"
            git tag -l "v*" --sort=-v:refname | head -10
            exit 1
          fi
  
  rollback:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Checkout version
        run: git checkout ${{ github.event.inputs.version }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Install EAS CLI
        run: npm install -g eas-cli
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install Sentry CLI
        run: npm install -g @sentry/cli
      
      - name: Set Environment Variables
        run: |
          echo "APP_ENV=production" >> $GITHUB_ENV
          echo "PROFILE=production" >> $GITHUB_ENV
          echo "SENTRY_ENVIRONMENT=production" >> $GITHUB_ENV
          echo "Using production environment for rollback"
      
      - name: Validate Sentry credentials
        run: |
          if [ -z "${{ secrets.SENTRY_AUTH_TOKEN }}" ] || [ -z "${{ secrets.SENTRY_ORG }}" ] || [ -z "${{ secrets.SENTRY_PROJECT }}" ]; then
            echo "::warning::Missing or incomplete Sentry credentials. Source maps upload may fail."
          else
            echo "Sentry credentials validated"
          fi
      
      - name: Build rollback version
        run: npx eas-cli build --platform all --profile production --non-interactive
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      
      - name: Manual Sentry Source Maps Upload
        if: success()
        run: |
          if [ -n "${{ secrets.SENTRY_AUTH_TOKEN }}" ] && [ -n "${{ secrets.SENTRY_ORG }}" ] && [ -n "${{ secrets.SENTRY_PROJECT }}" ]; then
            echo "Uploading source maps to Sentry for rollback version"
            VERSION=$(node -p "require('./app.json').expo.version")
            ROLLBACK_VERSION="rollback-$VERSION-${{ github.run_id }}"
            
            # Create a new release for the rollback
            sentry-cli releases new "$ROLLBACK_VERSION"
            sentry-cli releases set-commits --auto "$ROLLBACK_VERSION"
            
            # Find and upload source maps in the .expo directory
            find .expo -name "*.map" -type f -exec sentry-cli releases files "$ROLLBACK_VERSION" upload-sourcemaps --dist "$VERSION" {} \;
            
            sentry-cli releases finalize "$ROLLBACK_VERSION"
            echo "Source maps uploaded to Sentry for rollback version"
          else
            echo "::warning::Skipping source maps upload due to missing Sentry credentials"
          fi
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      
      - name: Create rollback release
        uses: softprops/action-gh-release@v1
        with:
          name: "Rollback to ${{ github.event.inputs.version }}"
          tag_name: "rollback-${{ github.event.inputs.version }}-${{ github.run_id }}"
          body: "This is an automated rollback to version ${{ github.event.inputs.version }}."
          draft: false
          prerelease: false
          files: |
            *.apk
            *.ipa
            *.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Notify Rollback
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ":warning: VividWealth app has been rolled back to version ${{ github.event.inputs.version }}!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 